package gt.gob.sat.uip.service_solicituduip.model;
// Generated 06-ago-2019 15:34:47 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Asignacion generated by hbm2java
 */
@Entity
@Table(name="asignacion"
    ,schema="sat_uip"
)
public class Asignacion  implements java.io.Serializable {


     private int idAsignacion;
     private String estatus;
     private int idCat;
     private int idOrdRevisor;
     private int idRevisor;

    public Asignacion() {
    }

    public Asignacion(int idAsignacion, String estatus, int idCat, int idOrdRevisor, int idRevisor) {
       this.idAsignacion = idAsignacion;
       this.estatus = estatus;
       this.idCat = idCat;
       this.idOrdRevisor = idOrdRevisor;
       this.idRevisor = idRevisor;
    }
   
     @Id 

    
    @Column(name="id_asignacion", unique=true, nullable=false)
    public int getIdAsignacion() {
        return this.idAsignacion;
    }
    
    public void setIdAsignacion(int idAsignacion) {
        this.idAsignacion = idAsignacion;
    }

    
    @Column(name="estatus", nullable=false, length=2)
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }

    
    @Column(name="id_cat", nullable=false)
    public int getIdCat() {
        return this.idCat;
    }
    
    public void setIdCat(int idCat) {
        this.idCat = idCat;
    }

    
    @Column(name="id_ord_revisor", nullable=false)
    public int getIdOrdRevisor() {
        return this.idOrdRevisor;
    }
    
    public void setIdOrdRevisor(int idOrdRevisor) {
        this.idOrdRevisor = idOrdRevisor;
    }

    
    @Column(name="id_revisor", nullable=false)
    public int getIdRevisor() {
        return this.idRevisor;
    }
    
    public void setIdRevisor(int idRevisor) {
        this.idRevisor = idRevisor;
    }




}


