package gt.gob.sat.uip.service_solicituduip.model;
// Generated 06-ago-2019 15:34:47 by Hibernate Tools 4.3.1


import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contribuyente generated by hbm2java
 */
@Entity
@Table(name="contribuyente"
    ,schema="sat_uip"
)
public class Contribuyente  implements java.io.Serializable {


     private BigInteger idContribuyente;
     private Integer idTipoContribuyente;
     private String nit;

    public Contribuyente() {
    }

	
    public Contribuyente(BigInteger idContribuyente, String nit) {
        this.idContribuyente = idContribuyente;
        this.nit = nit;
    }
    public Contribuyente(BigInteger idContribuyente, Integer idTipoContribuyente, String nit) {
       this.idContribuyente = idContribuyente;
       this.idTipoContribuyente = idTipoContribuyente;
       this.nit = nit;
    }
   
     @Id 

    
    @Column(name="id_contribuyente", unique=true, nullable=false)
    public BigInteger getIdContribuyente() {
        return this.idContribuyente;
    }
    
    public void setIdContribuyente(BigInteger idContribuyente) {
        this.idContribuyente = idContribuyente;
    }

    
    @Column(name="id_tipo_contribuyente")
    public Integer getIdTipoContribuyente() {
        return this.idTipoContribuyente;
    }
    
    public void setIdTipoContribuyente(Integer idTipoContribuyente) {
        this.idTipoContribuyente = idTipoContribuyente;
    }

    
    @Column(name="nit", nullable=false)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }




}


