package gt.gob.sat.uip.service_solicituduip.model;
// Generated 06-ago-2019 15:34:47 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DatosContacto generated by hbm2java
 */
@Entity
@Table(name="datos_contacto"
    ,schema="sat_uip"
)
public class DatosContacto  implements java.io.Serializable {


     private DatosContactoId id;

    public DatosContacto() {
    }

    public DatosContacto(DatosContactoId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idTipoContacto", column=@Column(name="id_tipo_contacto", nullable=false) ), 
        @AttributeOverride(name="detalleContacto", column=@Column(name="detalle_contacto", nullable=false, length=256) ), 
        @AttributeOverride(name="idSolicitud", column=@Column(name="id_solicitud") ) } )
    public DatosContactoId getId() {
        return this.id;
    }
    
    public void setId(DatosContactoId id) {
        this.id = id;
    }




}


