package gt.gob.sat.uip.service_solicituduip.model;
// Generated 06-ago-2019 15:34:47 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DatosContactoId generated by hbm2java
 */
@Embeddable
public class DatosContactoId  implements java.io.Serializable {


     private int idTipoContacto;
     private String detalleContacto;
     private Integer idSolicitud;

    public DatosContactoId() {
    }

	
    public DatosContactoId(int idTipoContacto, String detalleContacto) {
        this.idTipoContacto = idTipoContacto;
        this.detalleContacto = detalleContacto;
    }
    public DatosContactoId(int idTipoContacto, String detalleContacto, Integer idSolicitud) {
       this.idTipoContacto = idTipoContacto;
       this.detalleContacto = detalleContacto;
       this.idSolicitud = idSolicitud;
    }
   


    @Column(name="id_tipo_contacto", nullable=false)
    public int getIdTipoContacto() {
        return this.idTipoContacto;
    }
    
    public void setIdTipoContacto(int idTipoContacto) {
        this.idTipoContacto = idTipoContacto;
    }


    @Column(name="detalle_contacto", nullable=false, length=256)
    public String getDetalleContacto() {
        return this.detalleContacto;
    }
    
    public void setDetalleContacto(String detalleContacto) {
        this.detalleContacto = detalleContacto;
    }


    @Column(name="id_solicitud")
    public Integer getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(Integer idSolicitud) {
        this.idSolicitud = idSolicitud;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DatosContactoId) ) return false;
		 DatosContactoId castOther = ( DatosContactoId ) other; 
         
		 return (this.getIdTipoContacto()==castOther.getIdTipoContacto())
 && ( (this.getDetalleContacto()==castOther.getDetalleContacto()) || ( this.getDetalleContacto()!=null && castOther.getDetalleContacto()!=null && this.getDetalleContacto().equals(castOther.getDetalleContacto()) ) )
 && ( (this.getIdSolicitud()==castOther.getIdSolicitud()) || ( this.getIdSolicitud()!=null && castOther.getIdSolicitud()!=null && this.getIdSolicitud().equals(castOther.getIdSolicitud()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTipoContacto();
         result = 37 * result + ( getDetalleContacto() == null ? 0 : this.getDetalleContacto().hashCode() );
         result = 37 * result + ( getIdSolicitud() == null ? 0 : this.getIdSolicitud().hashCode() );
         return result;
   }   


}


