package gt.gob.sat.uip.service_solicituduip.model;
// Generated 06-ago-2019 15:34:47 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Estatus generated by hbm2java
 */
@Entity
@Table(name="estatus"
    ,schema="sat_uip"
)
public class Estatus  implements java.io.Serializable {


     private int idestatus;
     private String nombre;

    public Estatus() {
    }

    public Estatus(int idestatus, String nombre) {
       this.idestatus = idestatus;
       this.nombre = nombre;
    }
   
     @Id 

    
    @Column(name="idestatus", unique=true, nullable=false)
    public int getIdestatus() {
        return this.idestatus;
    }
    
    public void setIdestatus(int idestatus) {
        this.idestatus = idestatus;
    }

    
    @Column(name="nombre", nullable=false, length=40)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


