package gt.gob.sat.uip.service_solicituduip.model;
// Generated 06-ago-2019 15:34:47 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name="pais"
    ,schema="sat_uip"
)
public class Pais  implements java.io.Serializable {


     private int idPais;
     private String iso;
     private String nombre;

    public Pais() {
    }

	
    public Pais(int idPais) {
        this.idPais = idPais;
    }
    public Pais(int idPais, String iso, String nombre) {
       this.idPais = idPais;
       this.iso = iso;
       this.nombre = nombre;
    }
   
     @Id 

    
    @Column(name="id_pais", unique=true, nullable=false)
    public int getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(int idPais) {
        this.idPais = idPais;
    }

    
    @Column(name="iso")
    public String getIso() {
        return this.iso;
    }
    
    public void setIso(String iso) {
        this.iso = iso;
    }

    
    @Column(name="nombre")
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


