package gt.gob.sat.uip.service_solicituduip.model;
// Generated 06-ago-2019 15:34:47 by Hibernate Tools 4.3.1


import java.math.BigInteger;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PersonaJuridica generated by hbm2java
 */
@Entity
@Table(name="persona_juridica"
    ,schema="sat_uip"
)
public class PersonaJuridica  implements java.io.Serializable {


     private BigInteger idContribuyente;
     private String razonSocial;
     private Date vencimientoRepresentacion;

    public PersonaJuridica() {
    }

	
    public PersonaJuridica(BigInteger idContribuyente, String razonSocial) {
        this.idContribuyente = idContribuyente;
        this.razonSocial = razonSocial;
    }
    public PersonaJuridica(BigInteger idContribuyente, String razonSocial, Date vencimientoRepresentacion) {
       this.idContribuyente = idContribuyente;
       this.razonSocial = razonSocial;
       this.vencimientoRepresentacion = vencimientoRepresentacion;
    }
   
     @Id 

    
    @Column(name="id_contribuyente", unique=true, nullable=false)
    public BigInteger getIdContribuyente() {
        return this.idContribuyente;
    }
    
    public void setIdContribuyente(BigInteger idContribuyente) {
        this.idContribuyente = idContribuyente;
    }

    
    @Column(name="razon_social", nullable=false)
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="vencimiento_representacion", length=13)
    public Date getVencimientoRepresentacion() {
        return this.vencimientoRepresentacion;
    }
    
    public void setVencimientoRepresentacion(Date vencimientoRepresentacion) {
        this.vencimientoRepresentacion = vencimientoRepresentacion;
    }




}


