package gt.gob.sat.uip.service_solicituduip.model;
// Generated 06-ago-2019 15:34:47 by Hibernate Tools 4.3.1


import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PersonaNatural generated by hbm2java
 */
@Entity
@Table(name="persona_natural"
    ,schema="sat_uip"
)
public class PersonaNatural  implements java.io.Serializable {


     private BigInteger idPersonaNatural;
     private Integer idPaisEmisionPasaporte;
     private Integer idTipoIdentificacionOficial;
     private String numeroIdentificacion;
     private String primerApellido;
     private String primerNombre;
     private String segundoApellido;
     private String segundoNombre;
     private String tercerApellido;
     private String tercerNombre;

    public PersonaNatural() {
    }

	
    public PersonaNatural(BigInteger idPersonaNatural, String primerNombre) {
        this.idPersonaNatural = idPersonaNatural;
        this.primerNombre = primerNombre;
    }
    public PersonaNatural(BigInteger idPersonaNatural, Integer idPaisEmisionPasaporte, Integer idTipoIdentificacionOficial, String numeroIdentificacion, String primerApellido, String primerNombre, String segundoApellido, String segundoNombre, String tercerApellido, String tercerNombre) {
       this.idPersonaNatural = idPersonaNatural;
       this.idPaisEmisionPasaporte = idPaisEmisionPasaporte;
       this.idTipoIdentificacionOficial = idTipoIdentificacionOficial;
       this.numeroIdentificacion = numeroIdentificacion;
       this.primerApellido = primerApellido;
       this.primerNombre = primerNombre;
       this.segundoApellido = segundoApellido;
       this.segundoNombre = segundoNombre;
       this.tercerApellido = tercerApellido;
       this.tercerNombre = tercerNombre;
    }
   
     @Id 

    
    @Column(name="id_persona_natural", unique=true, nullable=false)
    public BigInteger getIdPersonaNatural() {
        return this.idPersonaNatural;
    }
    
    public void setIdPersonaNatural(BigInteger idPersonaNatural) {
        this.idPersonaNatural = idPersonaNatural;
    }

    
    @Column(name="id_pais_emision_pasaporte")
    public Integer getIdPaisEmisionPasaporte() {
        return this.idPaisEmisionPasaporte;
    }
    
    public void setIdPaisEmisionPasaporte(Integer idPaisEmisionPasaporte) {
        this.idPaisEmisionPasaporte = idPaisEmisionPasaporte;
    }

    
    @Column(name="id_tipo_identificacion_oficial")
    public Integer getIdTipoIdentificacionOficial() {
        return this.idTipoIdentificacionOficial;
    }
    
    public void setIdTipoIdentificacionOficial(Integer idTipoIdentificacionOficial) {
        this.idTipoIdentificacionOficial = idTipoIdentificacionOficial;
    }

    
    @Column(name="numero_identificacion")
    public String getNumeroIdentificacion() {
        return this.numeroIdentificacion;
    }
    
    public void setNumeroIdentificacion(String numeroIdentificacion) {
        this.numeroIdentificacion = numeroIdentificacion;
    }

    
    @Column(name="primer_apellido")
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }

    
    @Column(name="primer_nombre", nullable=false)
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }

    
    @Column(name="segundo_apellido")
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }

    
    @Column(name="segundo_nombre")
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }

    
    @Column(name="tercer_apellido")
    public String getTercerApellido() {
        return this.tercerApellido;
    }
    
    public void setTercerApellido(String tercerApellido) {
        this.tercerApellido = tercerApellido;
    }

    
    @Column(name="tercer_nombre")
    public String getTercerNombre() {
        return this.tercerNombre;
    }
    
    public void setTercerNombre(String tercerNombre) {
        this.tercerNombre = tercerNombre;
    }




}


