package gt.gob.sat.uip.service_solicituduip.model;
// Generated 06-ago-2019 15:34:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RazonCita generated by hbm2java
 */
@Entity
@Table(name="razon_cita"
    ,schema="sat_uip"
)
public class RazonCita  implements java.io.Serializable {


     private int idRazoncita;
     private Set<Cita> citas = new HashSet<Cita>(0);
     private String nombre;

    public RazonCita() {
    }

	
    public RazonCita(int idRazoncita) {
        this.idRazoncita = idRazoncita;
    }
    public RazonCita(int idRazoncita, Set<Cita> citas, String nombre) {
       this.idRazoncita = idRazoncita;
       this.citas = citas;
       this.nombre = nombre;
    }
   
     @Id 

    
    @Column(name="id_razoncita", unique=true, nullable=false)
    public int getIdRazoncita() {
        return this.idRazoncita;
    }
    
    public void setIdRazoncita(int idRazoncita) {
        this.idRazoncita = idRazoncita;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="razonCita")
    public Set<Cita> getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set<Cita> citas) {
        this.citas = citas;
    }

    
    @Column(name="nombre", length=40)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


