package gt.gob.sat.uip.service_solicituduip.model;
// Generated 06-ago-2019 15:34:47 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Resultado generated by hbm2java
 */
@Entity
@Table(name="resultado"
    ,schema="sat_uip"
)
public class Resultado  implements java.io.Serializable {


     private int idResultado;
     private String nombre;

    public Resultado() {
    }

    public Resultado(int idResultado, String nombre) {
       this.idResultado = idResultado;
       this.nombre = nombre;
    }
   
     @Id 

    
    @Column(name="id_resultado", unique=true, nullable=false)
    public int getIdResultado() {
        return this.idResultado;
    }
    
    public void setIdResultado(int idResultado) {
        this.idResultado = idResultado;
    }

    
    @Column(name="nombre", nullable=false, length=128)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


