package gt.gob.sat.uip.service_solicituduip.model;
// Generated 06-ago-2019 15:34:47 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SolicitudUip generated by hbm2java
 */
@Entity
@Table(name="solicitud_uip"
    ,schema="sat_uip"
)
public class SolicitudUip  implements java.io.Serializable {


     private SolicitudUipId id;

    public SolicitudUip() {
    }

    public SolicitudUip(SolicitudUipId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idCita", column=@Column(name="id_cita", nullable=false) ), 
        @AttributeOverride(name="idEstatus", column=@Column(name="id_estatus", nullable=false) ), 
        @AttributeOverride(name="idPersonaJuridica", column=@Column(name="id_persona_juridica", nullable=false) ), 
        @AttributeOverride(name="idPersonaNatural", column=@Column(name="id_persona_natural", nullable=false) ), 
        @AttributeOverride(name="idResultado", column=@Column(name="id_resultado", nullable=false) ), 
        @AttributeOverride(name="idSolicitud", column=@Column(name="id_solicitud", nullable=false) ), 
        @AttributeOverride(name="idTipoContacto", column=@Column(name="id_tipo_contacto", nullable=false) ), 
        @AttributeOverride(name="informacionAdicionalSolicitada", column=@Column(name="informacion_adicional_solicitada", nullable=false, length=512) ), 
        @AttributeOverride(name="informacionSolicitada", column=@Column(name="informacion_solicitada", nullable=false, length=512) ), 
        @AttributeOverride(name="numeroSolicitud", column=@Column(name="numero_solicitud", nullable=false, length=40) ) } )
    public SolicitudUipId getId() {
        return this.id;
    }
    
    public void setId(SolicitudUipId id) {
        this.id = id;
    }




}


