package gt.gob.sat.uip.service_solicituduip.model;
// Generated 06-ago-2019 15:34:47 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SolicitudUipId generated by hbm2java
 */
@Embeddable
public class SolicitudUipId  implements java.io.Serializable {


     private Integer idCita;
     private int idEstatus;
     private Integer idPersonaJuridica;
     private Integer idPersonaNatural;
     private Integer idResultado;
     private int idSolicitud;
     private String informacionAdicionalSolicitada;
     private String informacionSolicitada;
     private String numeroSolicitud;

    public SolicitudUipId() {
    }

    public SolicitudUipId(Integer idCita, int idEstatus, Integer idPersonaJuridica, Integer idPersonaNatural, Integer idResultado, int idSolicitud, int idTipoContacto, String informacionAdicionalSolicitada, String informacionSolicitada, String numeroSolicitud) {
       this.idCita = idCita;
       this.idEstatus = idEstatus;
       this.idPersonaJuridica = idPersonaJuridica;
       this.idPersonaNatural = idPersonaNatural;
       this.idResultado = idResultado;
       this.idSolicitud = idSolicitud;
       this.informacionAdicionalSolicitada = informacionAdicionalSolicitada;
       this.informacionSolicitada = informacionSolicitada;
       this.numeroSolicitud = numeroSolicitud;
    }
   


    @Column(name="id_cita", nullable=false)
    public Integer getIdCita() {
        return this.idCita;
    }
    
    public void setIdCita(Integer idCita) {
        this.idCita = idCita;
    }


    @Column(name="id_estatus", nullable=false)
    public int getIdEstatus() {
        return this.idEstatus;
    }
    
    public void setIdEstatus(int idEstatus) {
        this.idEstatus = idEstatus;
    }


    @Column(name="id_persona_juridica", nullable=false)
    public Integer getIdPersonaJuridica() {
        return this.idPersonaJuridica;
    }
    
    public void setIdPersonaJuridica(Integer idPersonaJuridica) {
        this.idPersonaJuridica = idPersonaJuridica;
    }


    @Column(name="id_persona_natural", nullable=false)
    public Integer getIdPersonaNatural() {
        return this.idPersonaNatural;
    }
    
    public void setIdPersonaNatural(Integer idPersonaNatural) {
        this.idPersonaNatural = idPersonaNatural;
    }


    @Column(name="id_resultado", nullable=false)
    public Integer getIdResultado() {
        return this.idResultado;
    }
    
    public void setIdResultado(Integer idResultado) {
        this.idResultado = idResultado;
    }


    @Column(name="id_solicitud", nullable=false)
    public int getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(int idSolicitud) {
        this.idSolicitud = idSolicitud;
    }


    @Column(name="informacion_adicional_solicitada", nullable=false, length=512)
    public String getInformacionAdicionalSolicitada() {
        return this.informacionAdicionalSolicitada;
    }
    
    public void setInformacionAdicionalSolicitada(String informacionAdicionalSolicitada) {
        this.informacionAdicionalSolicitada = informacionAdicionalSolicitada;
    }


    @Column(name="informacion_solicitada", nullable=false, length=512)
    public String getInformacionSolicitada() {
        return this.informacionSolicitada;
    }
    
    public void setInformacionSolicitada(String informacionSolicitada) {
        this.informacionSolicitada = informacionSolicitada;
    }


    @Column(name="numero_solicitud", nullable=false, length=40)
    public String getNumeroSolicitud() {
        return this.numeroSolicitud;
    }
    
    public void setNumeroSolicitud(String numeroSolicitud) {
        this.numeroSolicitud = numeroSolicitud;
    }




}


