package gt.gob.sat.uip.service_solicituduip.model;
// Generated 06-ago-2019 15:34:47 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,schema="test"
)
public class User  implements java.io.Serializable {


     private int id;
     private String email;
     private String name;

    public User() {
    }

	
    public User(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public User(int id, String email, String name) {
       this.id = id;
       this.email = email;
       this.name = name;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="email", length=60)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


