package gt.gob.sat.uip.service_asignacionesrevisores.model;
// Generated 29/07/2019 10:34:12 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CatRevisores generated by hbm2java
 */
@Entity
@Table(name="cat_revisores"
    ,schema="sat_uip"
)
public class CatRevisores  implements java.io.Serializable {


     private int idCat;
     private String descripcionCargo;
     private Integer ultimoAsignado;

    public CatRevisores() {
    }

	
    public CatRevisores(int idCat, String descripcionCargo) {
        this.idCat = idCat;
        this.descripcionCargo = descripcionCargo;
    }
    public CatRevisores(int idCat, String descripcionCargo, Integer ultimoAsignado) {
       this.idCat = idCat;
       this.descripcionCargo = descripcionCargo;
       this.ultimoAsignado = ultimoAsignado;
    }
   
     @Id 

    
    @Column(name="id_cat", unique=true, nullable=false)
    public int getIdCat() {
        return this.idCat;
    }
    
    public void setIdCat(int idCat) {
        this.idCat = idCat;
    }

    
    @Column(name="descripcion_cargo", nullable=false, length=100)
    public String getDescripcionCargo() {
        return this.descripcionCargo;
    }
    
    public void setDescripcionCargo(String descripcionCargo) {
        this.descripcionCargo = descripcionCargo;
    }

    
    @Column(name="ultimo_asignado")
    public Integer getUltimoAsignado() {
        return this.ultimoAsignado;
    }
    
    public void setUltimoAsignado(Integer ultimoAsignado) {
        this.ultimoAsignado = ultimoAsignado;
    }




}


