package gt.gob.sat.uip.service_asignacionesrevisores.model;
// Generated 29/07/2019 10:34:12 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ColaboradorRevisor generated by hbm2java
 */
@Entity
@Table(name="colaborador_revisor"
    ,schema="sat_uip"
)
public class ColaboradorRevisor  implements java.io.Serializable {


     private int idRevisor;
     private String nombre;
     private String correo;

    public ColaboradorRevisor() {
    }

    public ColaboradorRevisor(int idRevisor, String nombre, String correo) {
       this.idRevisor = idRevisor;
       this.nombre = nombre;
       this.correo = correo;
    }
   
     @Id 

    
    @Column(name="id_revisor", unique=true, nullable=false)
    public int getIdRevisor() {
        return this.idRevisor;
    }
    
    public void setIdRevisor(int idRevisor) {
        this.idRevisor = idRevisor;
    }

    
    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="correo", nullable=false, length=100)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }




}


